{% set name = "conda-index" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: afbf3850b2197ab4ceb7785bee462e063bd498488c185112477cbe4197e70aad

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - python
    - pip
  run:
    - python
    - click >=8
    - conda >=4.14.0
    - conda-package-streaming >=0.7.0
    - filelock
    - jinja2
    # https://github.com/conda/conda-index/blob/0.7.0/recipe/meta.yaml#L31
    - msgpack-python >=1.0.2
    - ruamel.yaml
    - zstandard

test:
  imports:
    - conda_index.index
  source_files:
    - tests
  requires:
    # https://github.com/conda/conda-index/blob/0.7.0/conda_index/plugin.py#L22
    - conda-build >=24.1
    # https://github.com/conda/conda-index/blob/0.7.0/recipe/meta.yaml#L37
    - conda-package-handling >=2.2.0
    - coverage
    - pip
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
    # "fsspec[http]" expands to 'http = ["aiohttp !=4.0.0a0, !=4.0.0a1"]''
    - fsspec
    - aiohttp !=4.0.0a0, !=4.0.0a1
  commands:
    - pip check
    - pytest -k test_index_on_single_subdir_1

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  description: |
    Create repodata.json for collections of conda packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - AndresGuzman-Ballen
    - dholth
    - jharlow-intel
    - kenodegard
