{% set name = "conda-index" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b096e34b048b494489ff41389ecc4b17b9f400dbf5b36ee2e39aa2558cc9a6c2

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - python
    - pip
  run:
    - python
    - click >=8
    - conda >=4.14.0
    - conda-package-streaming >=0.7.0
    - filelock
    - jinja2
    - msgpack-python
    - ruamel.yaml
    - zstandard

test:
  imports:
    - conda_index.index
  source_files:
    - tests
  requires:
    # Skip conda-build for py313 because conda-index is a cycle dependency
    - conda-build >=3.21.0  # [py<313]
    - conda-package-handling >=1.9.0
    - coverage
    - pip
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
    # "fsspec[http]" expands to 'http = ["aiohttp !=4.0.0a0, !=4.0.0a1"]''
    - fsspec
    - aiohttp !=4.0.0a0, !=4.0.0a1
  commands:
    - pip check
    - pytest -k test_index_on_single_subdir_1

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  description: |
    Create repodata.json for collections of conda packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - AndresGuzman-Ballen
    - dholth
    - jharlow-intel
    - kenodegard
